### ISSUE TITLE
Incorrect order with diacritics

### ISSUE THREAD

**Issue by cslee** [yobacca/natural-orderby#34]
The order is incorrect when the string contains diacritics
```
> orderBy(['b', 'd', 'f', 'A', 'C', 'E'])
[ 'A', 'C', 'E', 'b', 'd', 'f' ]
// correct

> orderBy(['b', 'd', 'f', 'A', 'Cé', 'E'])
[ 'A', 'b', 'Cé', 'E', 'd', 'f' ]
// incorrect
```

**Comment by yobacca** [comment]
Thanks for posting this issue!

The reason is that this library compares strings without unicode characters differently than strings with unicode characters.

If two strings do not contain unicode characters, they will be compared based on their corresponding ascii decimal value. Therefore upper case letters are sorted before lower case letters.

```
['b', 'C', 'A', 'c', 'a', 'B'].sort((a, b) => {
  if (a < b) {
    return -1;
  }
  if (a > b) {
    return 1;
  }
  return 0;
})
// ['A', 'B', 'C', 'a', 'b', 'c']
```

If two strings do contain unicode characters, they will be compared using [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare). This method is being aware of the relation of small and capital letters.

```
['b', 'C', 'A', 'c', 'a', 'B'].sort((a, b) => a.localeCompare(b))
// ['a', 'A', 'b', 'B', 'c', 'C']
```

If an array contains both strings with unicode characters and strings without unicode characters, the sorting is done partly based on the ascii decimal values and partly using `localeCompare`. That´s why the output of your second example looks weird.

This issue made me think about natural ordering of strings. For humans, the strings `"name"`, `"NAME"`, `"nAMe"` and `"Name"` differ only in upper and lower case, otherwise they are the same. This interpretation is based on a cultural convention, namely the knowledge of the relationship between capital and small letters. 

So the natural order of your examples should be as follows:

```
['b', 'd', 'f', 'A', 'C', 'E']
=> [ 'A', 'b', 'C', 'd', 'E', 'f' ]

['b', 'd', 'f', 'A', 'Cé', 'E']
=> [ 'A', 'b', 'Cé', 'd', 'E', 'f' ]
```

From this point of view, strings should generally be compared using localecompare and not based on their ascii decimal value. I would therefore suggest that we change this library accordingly.

But I would like to hear other opinions, because this would be a breaking change.

**Comment by cslee** [comment]
Thanks for your detailed explanation.

It makes sense that the letter case is not important in natural sorting. That's fine with me if the case sensitive option is removed.
