### ISSUE TITLE
Incorrect ordering of mixed-alphanumeric strings with leading 0s

### ISSUE THREAD

**Issue by baxtea** [yobacca/natural-orderby#57]
```
var naturalOrderby = require("natural-orderby")

naturalOrderby.orderBy(["05", "06", "07*", "08A", "09 B", "10", "11", "12A", "13"])
```

Expected result: no change. Actual result:

`["05", "06", "07*", "10", "11", "12A", "13", "08A", "09 B"]`

See https://runkit.com/embed/b88ooo12p3ap

I think I have the specifics pinned down in the title, but I'm not sure if that's quite it. I know [repeating the test with numbers ranging from 15 to 23](https://runkit.com/embed/2xkm7ws1ao11) behaves as expected, and I can't find any non-alphabetic characters that prompt the same error.

**Comment by yobacca** [comment]
Thanks for reporting this issue!

Currently a number with leading zeros is only parsed as a number, if it´s not followed by a letter to be able to sort filenames prefixed with numbers containing leading zeros (e.g. 001filename.txt, 01filename.txt).

So, in your case the numeric parts of the strings ´"08A"´ and ´"09 B"´ are kept as a string: `"08"` and `"09"`. That´s why they are sorted to the end, because the numeric parts of the other elements are getting parsed to numeric values before sort.

I´ll fix this during the following week by keeping the ability to sort filenames prefixed with numbers containing leading zeros.
